version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fwv_raura}
      MYSQL_USER: ${MYSQL_USER:-fwvuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fwvpassword}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "3306:3306"
    networks:
      - fwv-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER:-fwvuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fwvpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fwv_raura}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fwv-network

volumes:
  mysql_data:

networks:
  fwv-network:
    driver: bridge
